name: wagyufari
description: Muhammad Ghifari Yusuf

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^0.0.1+2
  data_connection_checker: ^0.3.4
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.15
  email_validator: ^2.1.16
  sensors_plus: ^1.3.4+1
  share_plus: ^4.0.1
  device_info_plus: ^3.2.3
  flutter_svg: ^1.1.4
  scrollable_positioned_list: ^0.3.2
  blur: ^3.0.0
  after_layout: ^1.2.0

  google_fonts: ^3.0.1
  material_segmented_control: ^3.1.2
  modal_bottom_sheet: ^2.1.2

  flutter_phoenix: ^1.1.0
  scroll_to_index: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2

  visibility_detector: ^0.3.3
  google_sign_in: ^5.4.3
  font_awesome_flutter: ^10.3.0
  animated_text_kit: ^4.2.2
  parallax_animation: ^0.0.3

  flutter_circular_text: ^0.3.1
  url_launcher: ^6.1.8
  flutter_layout_grid: ^2.0.1
  get: ^4.6.5
  flutter_bloc: ^8.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpeg
    - assets/gradient.jpg
    - assets/happy5_logo.png
    - assets/apple_logo.png
    - assets/verified.png
    - assets/android_logo.png
    - assets/linkedin.png
    - assets/linkedin_selected.png
    - assets/ig.png
    - assets/ig_selected.png
    - assets/github.png
    - assets/dzikirqu.png
    - assets/github_selected.png
    - assets/iphone12.png
    - assets/pocof3.png
    - assets/xiaomi4k.png
    - assets/xiaomi34.png
    - assets/leband.png
    - assets/ultimo.png
    - assets/mxkeys.png
    - assets/mxmaster.png
    - assets/lumiarm.png
    - assets/standingdesk.png
    - assets/razerbarx.png
    - assets/mbam1.png
    - assets/mbstand.png
    - assets/lention.png
    - assets/setup.jpeg
