name: wagyufari
description: Muhammad Ghifari Yusuf

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^0.0.1+2
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.15
  email_validator: ^2.1.16
  sensors_plus: ^1.3.4+1
  share_plus: ^4.0.1
  device_info_plus: ^3.2.3
  flutter_svg: ^2.0.0+1
  scrollable_positioned_list: ^0.3.2
  blur: ^3.0.0
  after_layout: ^1.2.0

  google_fonts: ^4.0.3
  material_segmented_control: ^3.1.2
  modal_bottom_sheet: ^2.1.2
  video_player: ^2.5.1

  flutter_phoenix: ^1.1.0
  scroll_to_index: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2

  visibility_detector: ^0.3.3
  google_sign_in: ^5.4.3
  font_awesome_flutter: ^10.3.0
  animated_text_kit: ^4.2.2
  parallax_animation: ^0.0.3

  flutter_circular_text: ^0.3.1
  url_launcher: ^6.1.8
  flutter_layout_grid: ^2.0.1
  go_router: ^6.0.3
  flutter_bloc: ^8.1.1
  marquee: ^2.2.3

  flutter_native_splash: ^2.2.17
#  flutter_launcher_icons: ^0.11.0

  flutter_localizations:
    sdk: flutter

#flutter_native_splash:
#  color: "#FFFFFF"
#  image: "assets/circleprimary.png"

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/circleprimary.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/circleprimary.png"

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpeg
    - assets/gradient.jpg
    - assets/happy5_logo.png
    - assets/apple_logo.png
    - assets/verified.png
    - assets/android_logo.png
    - assets/linkedin.png
    - assets/linkedin_selected.png
    - assets/ig.png
    - assets/ig_selected.png
    - assets/github.png
    - assets/dzikirqu.png
    - assets/github_selected.png
    - assets/iphone12.png
    - assets/pocof3.png
    - assets/xiaomi4k.png
    - assets/xiaomi34.png
    - assets/leband.png
    - assets/ultimo.png
    - assets/mxkeys.png
    - assets/mxmaster.png
    - assets/lumiarm.png
    - assets/standingdesk.png
    - assets/razerbarx.png
    - assets/mbam1.png
    - assets/mbstand.png
    - assets/lention.png
    - assets/logo.svg
    - assets/setup.jpeg
    - assets/circleprimary.png
    - assets/flutterdev.png
    - assets/androidev.png
    - assets/iosdev.png
    - assets/prodisplay.png
    - assets/code.png
    - assets/terminal.svg
    - assets/mention3.gif
    - assets/mention1.gif
    - assets/mention2.gif
    - assets/tree3.gif
    - assets/tree2.gif
    - assets/tree1.gif
    - assets/drag1.gif
    - assets/drag2.gif
    - assets/drag3.gif
    - assets/intro1.gif
    - assets/intro2.gif
    - assets/intro3.gif
    - assets/sheet1.gif
    - assets/sheet2.gif
    - assets/sheet3.gif
    - assets/charts1.gif
    - assets/charts2.gif
    - assets/charts3.gif
    - assets/iphone_frame.png
